# Topic mới nổi: kiểm tra pane repo, phím tab, và phím s đổi sort.
typ("claude code memory", 0.03)
os.write(fd, b"\r")
pump(9.0)
snapshot("mac dinh: sap theo diem")
os.write(fd, b"s")
pump(0.5)
snapshot("bam s: sap theo relevance")
os.write(fd, b"\t")
pump(0.5)
typ("jj", 0.15)
snapshot("tab sang pane repo")
os.write(fd, b"q")
pump(1.0)
