# Kiểm tra ba pane, nhóm phụ lục và sàn điểm HN.
typ("speculative decoding", 0.03)
os.write(fd, b"\r")
pump(12.0)
snapshot("pane bai: HN xep hang, arXiv la phu luc diem '-'")
os.write(fd, b"G")
pump(0.4)
snapshot("cuoi danh sach: nhom arXiv")
os.write(fd, b"\t")
pump(0.4)
snapshot("tab 1: pane repo (GitHub search theo query)")
os.write(fd, b"\t")
pump(0.4)
snapshot("tab 2: pane trending (khong theo query, +sao tuan)")
os.write(fd, b"\t")
pump(0.4)
snapshot("tab 3: vong lai pane bai")
os.write(fd, b"q")
pump(1.0)
